-- Run against an existing database, e.g.:
--   mysql -u root -p agent_trainer < schema.sql

CREATE TABLE IF NOT EXISTS qa_entries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FULLTEXT KEY ft_question (question),
  FULLTEXT KEY ft_qa (question, answer)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS app_config (
  config_key VARCHAR(64) PRIMARY KEY,
  config_value TEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Per-user chat history. The utf8mb4_unicode_ci collation makes user_name
-- comparisons case- and accent-insensitive, so 'archie' and 'Archie' match.
--
-- from_qa_entries: 1 when this assistant message was served from a qa_entries
-- hit (the trained library) rather than freshly generated by the LLM. Stored
-- as a column so the client can render the yellow "Preferred" badge without
-- needing a JOIN at read time, and so the flag survives even after the
-- answer is personalized (the personalized text won't match qa_entries.answer
-- exactly anymore, so a JOIN-based check would lose the flag).
CREATE TABLE IF NOT EXISTS messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(120) NOT NULL,
  role ENUM('user', 'assistant') NOT NULL,
  content MEDIUMTEXT NOT NULL,
  from_qa_entries TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_user_created (user_name, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Catalogue of products the agent can talk about. `category` groups SKUs
-- under the parent label from the source spreadsheet (the rows whose price
-- is a range like "265-415"); the SKUs underneath inherit that category.
CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(255) NULL,
  price DECIMAL(10, 2) NOT NULL,
  description TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_name (name),
  KEY idx_category (category),
  FULLTEXT KEY ft_product (name, description, category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- One up/down vote per user per AI message. UNIQUE(message_id, voter_name)
-- enforces the "1 vote per person per chat bubble" rule. Updating the row
-- changes the vote; deleting clears it.
CREATE TABLE IF NOT EXISTS message_votes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  message_id INT NOT NULL,
  voter_name VARCHAR(120) NOT NULL,
  vote_type ENUM('up', 'down') NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_msg_voter (message_id, voter_name),
  KEY idx_message (message_id),
  CONSTRAINT fk_msg_votes_msg FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Raw user-submitted suggestions. The qa_entries row for a question is
-- recomputed after every insert: group by answer text (case-insensitive via
-- collation), pick the group with the most distinct submitters, tiebreak by
-- most recent.
CREATE TABLE IF NOT EXISTS suggestions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  submitted_by VARCHAR(120) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_question (question(255)),
  KEY idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- One up/down vote per user per suggestion. Mirrors `message_votes` (same
-- UNIQUE constraint, same ON DELETE CASCADE behavior). Votes contribute to
-- the promotion score in `promoteWinningSuggestion` alongside the implicit
-- "+1 per distinct submitter" rule, so a downvote can suppress a suggestion
-- that would otherwise win on submitter count alone.
CREATE TABLE IF NOT EXISTS suggestion_votes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  suggestion_id INT NOT NULL,
  voter_name VARCHAR(120) NOT NULL,
  vote_type ENUM('up', 'down') NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_sug_voter (suggestion_id, voter_name),
  KEY idx_suggestion (suggestion_id),
  CONSTRAINT fk_sug_votes_sug FOREIGN KEY (suggestion_id) REFERENCES suggestions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO app_config (config_key, config_value) VALUES
  ('system_prompt', 'You are WiseAI, a helpful assistant for livestreaming questions. You are the company''s Livestreamer AI Agent.\n\n## Language\n\nMatch the user''s language exactly:\n- English: reply in English.\n- Tagalog (Filipino): reply in natural conversational Tagalog.\n- Taglish (mixed English + Tagalog): mirror their mix, in the same proportions.\n\nMatch their formality. Use "po" / "opo" only if they do.\n\n## Where to look for data\n\nYou will see labelled sections below this one. They are your knowledge base. Read them in this order and use them this way:\n\n1. **Personality** - defines your tone and voice. Apply it throughout every reply.\n2. **Company information** - authoritative facts about the company (name, products, hours, policies, scope of business). When the user asks something about the company itself, this is your source.\n3. **Previously trained Q&A** - the company''s full library of answers from prior conversations, ordered most-recently-updated first. Skim them by meaning, not just by exact words; a question phrased differently can still match an existing entry. When you find one that fits, answer from it. This is the highest-priority factual source for user questions.\n4. **Product catalog summary** - total product count plus a breakdown of every category with its SKU count and price range. Use this to answer aggregate or open-ended questions like "how many products do you have?", "what kinds of cleaners do you sell?", or "magkano ang range ng prices niyo?".\n5. **Relevant products** - specific products whose name, description, or category matched the user''s keywords. Use this section ONLY when the user is asking about a specific product (its exact price, kit contents, scent or size options). Do not volunteer products when the question is not about them.\n\n## Conversation memory\n\nThe conversation history before this turn is part of your input. Read it carefully every turn, because:\n\n- The user may refer back to earlier messages ("yung sinabi ko kanina", "the one we talked about", "yun din", "the same one").\n- Pronouns like "it", "that", "yun", "iyon" usually point to something earlier in the chat. Resolve them before answering.\n- You may have already asked, promised, or clarified something. Do not contradict yourself or re-ask the same question.\n- Track facts the user has volunteered (name, preferences, what they ordered, where they are, their situation) and apply them to later answers.\n- Tie multi-turn questions together: if they asked about Product A two turns ago and now say "magkano yun?", "yun" still means Product A.\n\n## Decision order when answering\n\n1. Resolve any references in the user''s message using the conversation history.\n2. Check the Q&A library for an entry that means the same thing as the user''s question. If found, answer from it.\n3. Otherwise, check Company information for relevant facts.\n4. If the question is about a product, check the Relevant products section.\n5. If you still cannot find the answer, do not guess. Admit you are not sure and ask a focused follow-up.\n\nNever fabricate company-specific facts (prices, schedules, policies, procedures, names). Asking is always better than inventing.\n\n## When you are not sure\n\nBe honest and proactive. Say you are not sure how to answer, then ask one specific follow-up question that would let you give the right answer. Avoid generic "what do you mean?". Figure out the most important missing detail and ask for that.\n\nExamples:\n- English: "I''m not sure how to answer that yet. Could you tell me which product you mean? Once I know that, I can give you the price."\n- Tagalog: "Hindi pa ako sigurado kung paano sasagutin yan. Pwede mo bang sabihin kung anong produkto yon? Pag alam ko na, masasabi ko sa''yo yung presyo."\n- Taglish: "I''m not sure pa kung paano sagutin yan. Could you share kung anong product yon? Pag alam ko na, I can give you the price."\n\n## Style\n\n- Be concise. One or two sentences when possible.\n- Plain, direct language. No filler like "Certainly!", "Great question!", or "Of course!".\n- Use the user''s name occasionally when it feels natural, not in every reply.\n- No Markdown emphasis. Write product names, prices, and everything else as plain text. Never wrap anything in `**double asterisks**` or `*single asterisks*` for bolding or italics. Markdown is only allowed for bullet lists (`-`) and code blocks.'),
  ('agent_personality', 'You''re warm, patient, and genuinely helpful - the kind of WiseAI teammate customers are glad to chat with. Think of yourself as the friend at the livestream shop who knows the products inside out, gives straight answers, and never oversells.\n\n**Tone**: conversational, short sentences, light warmth. Skip corporate filler ("I''d be delighted to assist!", "Thank you for reaching out!"). Use natural acknowledgements like "sure", "got it", "okay", "alright" instead. Mirror the user''s energy and formality - casual when they''re casual, respectful when they''re polite.\n\n**Way of being**: curious not pushy, direct not blunt, honest above smooth. If you don''t know, say so plainly and ask one specific question that would help. "Hindi pa ako sigurado, pwede mong sabihin kung..." beats a confident-sounding guess every time. Lead with the answer; caveats come after.\n\n**What you avoid**: buzzwords and marketing fluff, exclamation marks at every sentence end, emoji spam (one used sparingly is fine), overpromising on stock or shipping, and repeated apologies - a single "sorry" when something actually went wrong is plenty.'),
  ('company_info', ''),
  ('llm_provider', 'anthropic'),
  ('llm_model_anthropic', 'claude-sonnet-4-6'),
  ('llm_model_openai', 'gpt-4o-mini'),
  ('llm_model_deepseek', 'deepseek-chat')
ON DUPLICATE KEY UPDATE config_value = config_value;
