import { useEffect, useLayoutEffect, useRef, useState } from 'react';
import { api, type SuggestionRow, type StoredMessage } from '../api/client';
import { useUserName } from '../lib/userName';

// Page size for the chat-history lazy loader. Matches the server's default
// when no explicit `limit` is passed.
const MESSAGES_PAGE_SIZE = 30;
// When the user scrolls within this many pixels of the top, trigger a fetch
// of the next older page (if any remain). 100px gives a smooth experience.
// The prepend happens before they reach scrollTop=0 and "stick" at the edge.
const LAZY_LOAD_THRESHOLD_PX = 100;

// Server row -> in-component message shape. Used by both the initial fetch
// and the lazy loader. `from_qa_entries` is coerced to a strict boolean
// because MySQL returns TINYINT(1) as 0/1; `suggestion_count` is forced
// numeric because of similar string-vs-number quirks across drivers.
function storedToMessage(m: StoredMessage): Message {
  return {
    id: m.id,
    role: m.role,
    content: m.content,
    my_vote: m.my_vote,
    suggestion_count: Number(m.suggestion_count ?? 0),
    from_qa_entries: Boolean(m.from_qa_entries)
  };
}

type VoteState = 'up' | 'down' | null;
// 'system' is a client-only role used to render command output (like the
// `/users` list). System messages are never sent to the server or persisted;
// they disappear on reload.
type MessageRole = 'user' | 'assistant' | 'system';

interface SlashCommand {
  name: string;            // including the leading slash, e.g. "/restart"
  description: string;     // shown in the dropdown
}

const SLASH_COMMANDS: SlashCommand[] = [
  { name: '/restart',        description: 'Deletes all the conversations of the account.' },
  { name: '/clear-votes',    description: 'Clears all your votes on all messages.' },
  { name: '/clean',          description: 'Clears the visible messages on this device only. Data in the database is untouched; messages return on reload.' },
  { name: '/delete-account', description: 'Deletes the account and all associated data, then returns to the name prompt.' },
  { name: '/users',          description: 'Lists all existing users.' }
];

interface Message {
  id?: number;
  role: MessageRole;
  content: string;
  my_vote?: VoteState;
  // Number of rows in the `suggestions` table for this assistant message's
  // preceding user question. Used to gate the "See other suggestions" button:
  // it's only shown when count > 1 (i.e. there are multiple alternatives to
  // browse). Undefined / 0 for user bubbles.
  suggestion_count?: number;
  // True when this assistant message's content matches the current
  // qa_entries answer for its preceding user question — i.e. it was served
  // from the trained library, not freshly generated by the LLM. Used to
  // render the yellow "Preferred" badge above the bubble.
  from_qa_entries?: boolean;
}

const TEXTAREA_MAX_HEIGHT = 200;
const MULTILINE_THRESHOLD = 40;

function BulbIcon({ className = 'w-4 h-4' }: { className?: string }) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className} aria-hidden="true">
      <path strokeLinecap="round" strokeLinejoin="round" d="M12 18v-5.25m0 0a6.01 6.01 0 0 0 1.5-.189m-1.5.189a6.01 6.01 0 0 1-1.5-.189m3.75 7.478a12.06 12.06 0 0 1-4.5 0m3.75 2.383a14.406 14.406 0 0 1-3 0M14.25 18v-.192c0-.983.658-1.823 1.508-2.316a7.5 7.5 0 1 0-7.517 0c.85.493 1.509 1.333 1.509 2.316V18" />
    </svg>
  );
}

function MessageIcon({ className = 'w-4 h-4' }: { className?: string }) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className} aria-hidden="true">
      <path strokeLinecap="round" strokeLinejoin="round" d="M8.625 12a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm0 0H8.25m4.125 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm0 0H12m4.125 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm0 0h-.375M21 12c0 4.556-4.03 8.25-9 8.25a9.764 9.764 0 0 1-2.555-.337A5.972 5.972 0 0 1 5.41 20.97a5.969 5.969 0 0 1-.474-.065 4.48 4.48 0 0 0 .978-2.025c.09-.457-.133-.901-.467-1.226C3.93 16.178 3 14.189 3 12c0-4.556 4.03-8.25 9-8.25s9 3.694 9 8.25Z" />
    </svg>
  );
}

function CopyIcon({ className = 'w-4 h-4' }: { className?: string }) {
  // Matches ChatGPT: two overlapping rounded squares (Lucide "copy" glyph).
  return (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" className={className} aria-hidden="true">
      <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
    </svg>
  );
}

function CheckIcon({ className = 'w-4 h-4' }: { className?: string }) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className={className} aria-hidden="true">
      <path strokeLinecap="round" strokeLinejoin="round" d="m4.5 12.75 6 6 9-13.5" />
    </svg>
  );
}

function StarIcon({ className = 'w-3 h-3' }: { className?: string }) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className={className} aria-hidden="true">
      <path fillRule="evenodd" d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.007Z" clipRule="evenodd" />
    </svg>
  );
}

function EditIcon({ className = 'w-3 h-3' }: { className?: string }) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.8} stroke="currentColor" className={className} aria-hidden="true">
      <path strokeLinecap="round" strokeLinejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125" />
    </svg>
  );
}

function PreferredBadge() {
  return (
    <div
      className="ml-4 inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-yellow-400/15 border border-yellow-400/50 text-yellow-300 text-[10px] font-semibold uppercase tracking-wide"
      title="This answer comes from the trained Q&A library."
    >
      <StarIcon className="w-3 h-3" />
      <span>Preferred</span>
    </div>
  );
}

function ThumbUpIcon({ className = 'w-4 h-4', filled = false }: { className?: string; filled?: boolean }) {
  if (filled) {
    return (
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className={className} aria-hidden="true">
        <path d="M7.493 18.5c-.425 0-.82-.236-.975-.632A7.48 7.48 0 0 1 6 15.125c0-1.75.599-3.358 1.602-4.634.151-.192.373-.309.6-.397.473-.183.89-.514 1.212-.924a9.042 9.042 0 0 1 2.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 0 0 .322-1.672V2.75A.75.75 0 0 1 15 2a2.25 2.25 0 0 1 2.25 2.25c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 0 1-2.649 7.521c-.388.482-.987.729-1.605.729H14.23c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 0 0-1.423-.23h-.777ZM2.331 10.977a11.969 11.969 0 0 0-.831 4.398 12 12 0 0 0 .52 3.507c.26.85 1.084 1.368 1.973 1.368H4.9c.445 0 .72-.498.523-.898a8.963 8.963 0 0 1-.924-3.977c0-1.708.476-3.305 1.302-4.666.245-.403-.028-.959-.5-.959H4.25c-.832 0-1.612.453-1.918 1.227Z" />
      </svg>
    );
  }
  return (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className={className} aria-hidden="true">
      <path strokeLinecap="round" strokeLinejoin="round" d="M6.633 10.25c.806 0 1.533-.446 2.031-1.08a9.041 9.041 0 0 1 2.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 0 0 .322-1.672V2.75a.75.75 0 0 1 .75-.75 2.25 2.25 0 0 1 2.25 2.25c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282m0 0h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 0 1-2.649 7.521c-.388.482-.987.729-1.605.729H13.48c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 0 0-1.423-.23H5.904m10.598-9.75H14.25M5.904 18.5c.083.205.173.405.27.602.197.4-.078.898-.523.898h-.908c-.889 0-1.713-.518-1.972-1.368a12 12 0 0 1-.521-3.507c0-1.553.295-3.036.831-4.398C3.387 9.953 4.167 9.5 5 9.5h1.053c.472 0 .745.556.5.96a8.958 8.958 0 0 0-1.302 4.665c0 1.194.232 2.333.654 3.375Z" />
    </svg>
  );
}

function ThumbDownIcon({ className = 'w-4 h-4', filled = false }: { className?: string; filled?: boolean }) {
  if (filled) {
    return (
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className={className} aria-hidden="true">
        <path d="M15.73 5.5h1.035A7.465 7.465 0 0 1 18 9.625a7.465 7.465 0 0 1-1.235 4.125h-.148c-.806 0-1.534.446-2.031 1.08a9.04 9.04 0 0 1-2.861 2.4c-.723.384-1.35.956-1.653 1.715a4.498 4.498 0 0 0-.322 1.672v.633A.75.75 0 0 1 9 22a2.25 2.25 0 0 1-2.25-2.25c0-1.152.26-2.243.723-3.218.266-.558-.107-1.282-.725-1.282H3.622c-1.026 0-1.945-.694-2.054-1.715A12.137 12.137 0 0 1 1.5 12.25c0-2.848.992-5.464 2.649-7.521C4.537 4.247 5.136 4 5.754 4H9.77a4.5 4.5 0 0 1 1.423.23l3.114 1.04a4.5 4.5 0 0 0 1.423.23ZM21.669 14.023c.536-1.362.831-2.845.831-4.398 0-1.22-.182-2.398-.52-3.507-.26-.85-1.084-1.368-1.973-1.368H19.1c-.445 0-.72.498-.523.898.591 1.2.924 2.55.924 3.977a8.959 8.959 0 0 1-1.302 4.666c-.245.403.028.959.5.959h1.053c.832 0 1.612-.453 1.918-1.227Z" />
      </svg>
    );
  }
  return (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className={className} aria-hidden="true">
      <path strokeLinecap="round" strokeLinejoin="round" d="M7.498 15.25H4.372c-1.026 0-1.945-.694-2.054-1.715a12.137 12.137 0 0 1-.068-1.285c0-2.848.992-5.464 2.649-7.521C5.287 4.247 5.886 4 6.504 4h4.016a4.5 4.5 0 0 1 1.423.23l3.114 1.04a4.5 4.5 0 0 0 1.423.23h1.294M7.498 15.25c.618 0 .991.724.725 1.282A7.471 7.471 0 0 0 7.5 19.75 2.25 2.25 0 0 0 9.75 22a.75.75 0 0 0 .75-.75v-.633c0-.573.11-1.14.322-1.672.304-.76.93-1.33 1.653-1.715a9.04 9.04 0 0 0 2.86-2.4c.498-.634 1.226-1.08 2.032-1.08h.384m-10.253 1.5H9.7m8.075-9.75c.01.05.027.1.05.148.593 1.2.925 2.55.925 3.977 0 1.487-.36 2.89-.999 4.125m.023-8.25c-.076-.365.183-.75.575-.75h.908c.889 0 1.713.518 1.972 1.368.339 1.11.521 2.287.521 3.507 0 1.553-.295 3.036-.831 4.398-.306.774-1.086 1.227-1.918 1.227h-1.053c-.472 0-.745-.556-.5-.96a8.95 8.95 0 0 0 .303-.54" />
    </svg>
  );
}

export default function Chat() {
  const { name, clearName } = useUserName();
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [isMultiLine, setIsMultiLine] = useState(false);
  // The bubble the user clicked Suggest on. Tracks both the question text
  // (for the API call) AND the assistant message id (so the server can rewrite
  // that specific bubble in place when our suggestion wins promotion).
  const [replyTo, setReplyTo] = useState<{ question: string; assistantMessageId: number | null } | null>(null);
  const [suggestStatus, setSuggestStatus] = useState<string | null>(null);
  // Tracks the most-recently clicked vote so we can scope the pop animation
  // to that single button without re-animating history-loaded votes on mount.
  const [animTrigger, setAnimTrigger] = useState<{ messageId: number; voteType: 'up' | 'down'; key: number } | null>(null);
  // Per-message-id map of fetched suggestion rows, populated lazily when the
  // user expands the "See other suggestions" panel for a given AI reply.
  const [suggestionsByMessage, setSuggestionsByMessage] = useState<Record<number, SuggestionRow[]>>({});
  // Set of assistant message ids whose suggestion panel is currently open.
  const [openSuggestionsFor, setOpenSuggestionsFor] = useState<Set<number>>(new Set());
  // Per-message-id loading flag for the suggestions fetch.
  const [loadingSuggestionsFor, setLoadingSuggestionsFor] = useState<Set<number>>(new Set());
  // Per-message-index "just copied" flag; the copy button swaps to a checkmark
  // for ~1.5s after a successful copy. Keyed by index (not message id) so the
  // feedback works even on freshly-sent user bubbles whose server id hasn't
  // arrived yet.
  const [copiedIdx, setCopiedIdx] = useState<number | null>(null);
  const copyResetTimerRef = useRef<number | null>(null);
  // Slash-command palette: shown when the input starts with `/` and we're not
  // in reply (suggestion) mode. The palette is purely an aid — Enter still
  // triggers `submit()`, which detects exact command matches and routes them
  // to `executeCommand` instead of the chat / suggestion flows.
  const [commandIndex, setCommandIndex] = useState(0);
  // Inline-edit state for the suggestion thread. Keyed by suggestion id:
  // presence in the map means "this row is being edited"; the value is the
  // in-progress draft text.
  const [editingSuggestion, setEditingSuggestion] = useState<Record<number, string>>({});
  // Set of suggestion ids that are showing the "edit will remove all votes"
  // confirmation banner. Distinct from editing state because we only flip
  // into editing after the user clicks Continue. Cancel just clears the set.
  const [confirmingEditFor, setConfirmingEditFor] = useState<Set<number>>(new Set());
  // Per-suggestion-id "just copied" flag (mirrors copiedIdx but for the
  // suggestion thread).
  const [copiedSuggestionId, setCopiedSuggestionId] = useState<number | null>(null);
  const copiedSuggestionTimerRef = useRef<number | null>(null);
  const scrollRef = useRef<HTMLDivElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  // Tracks how many messages we'd already auto-scrolled past, so we only
  // scroll when a new message is appended (not when an existing one is
  // mutated, e.g. by a vote update).
  const lastScrolledCountRef = useRef(0);
  // Lazy-loading state. `hasMoreOlder` reflects the server's `has_more` flag
  // from the most recent fetch — true when older history exists below our
  // current oldest message. `loadingOlder` guards against double-fetching
  // when the scroll handler fires repeatedly while a request is in flight.
  const [hasMoreOlder, setHasMoreOlder] = useState(false);
  const [loadingOlder, setLoadingOlder] = useState(false);
  // When we prepend a page of older messages, we capture the scroll
  // container's `scrollHeight` BEFORE the prepend renders, then in
  // useLayoutEffect compute `newScrollHeight - previousHeight` and set
  // scrollTop to that. Net effect: the user's currently-visible content
  // stays anchored to the same screen position while new rows materialise
  // above. Without this, the viewport would jump to the top of the page.
  const scrollAdjustRef = useRef<{ previousHeight: number } | null>(null);

  useEffect(() => {
    const ta = textareaRef.current;
    if (!ta) return;
    ta.style.height = 'auto';
    const sh = ta.scrollHeight;
    if (input === '') {
      setIsMultiLine(false);
    } else if (sh > MULTILINE_THRESHOLD) {
      setIsMultiLine(true);
    }
    const needsScroll = sh > TEXTAREA_MAX_HEIGHT;
    ta.style.overflowY = needsScroll ? 'auto' : 'hidden';
    ta.style.height = `${Math.min(sh, TEXTAREA_MAX_HEIGHT)}px`;
  }, [input, isMultiLine]);

  // Reset the command palette highlight to the first row whenever the input
  // changes — otherwise a stale index could point past the filtered list.
  useEffect(() => {
    setCommandIndex(0);
  }, [input]);

  useLayoutEffect(() => {
    // Prepend branch: a lazy-load just inserted older messages at the top.
    // Restore the user's visible position by setting scrollTop to the height
    // delta. Runs synchronously before paint so there's no flicker.
    if (scrollAdjustRef.current) {
      const { previousHeight } = scrollAdjustRef.current;
      scrollAdjustRef.current = null;
      const el = scrollRef.current;
      if (el) {
        el.scrollTop = el.scrollHeight - previousHeight;
      }
      return;
    }
    // Append-or-loading branch: scroll to bottom when a new message appears
    // at the tail OR when the "Thinking..." indicator toggles. Vote toggles
    // mutate an existing message in place (length unchanged) and shouldn't
    // yank the viewport down.
    const isNewMessage = messages.length > lastScrolledCountRef.current;
    lastScrolledCountRef.current = messages.length;
    if (isNewMessage || loading) {
      scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: 'smooth' });
    }
  }, [messages, loading]);

  useEffect(() => {
    if (!name) return;
    let cancelled = false;
    api
      .getMessages({ user_name: name, limit: MESSAGES_PAGE_SIZE })
      .then(({ messages: stored, has_more }) => {
        if (cancelled) return;
        setMessages(stored.map(storedToMessage));
        setHasMoreOlder(has_more);
      })
      .catch((err: Error) => {
        console.error('Failed to load chat history:', err);
      });
    return () => {
      cancelled = true;
    };
  }, [name]);

  async function loadOlderMessages() {
    if (!name || !hasMoreOlder || loadingOlder) return;
    const oldest = messages[0];
    if (!oldest || oldest.id === undefined) return;

    setLoadingOlder(true);
    // Capture the scroll container's current height BEFORE we mutate state.
    // The useLayoutEffect will diff against this to keep the user anchored.
    const el = scrollRef.current;
    scrollAdjustRef.current = { previousHeight: el?.scrollHeight ?? 0 };
    try {
      const { messages: older, has_more } = await api.getMessages({
        user_name: name,
        before_id: oldest.id,
        limit: MESSAGES_PAGE_SIZE
      });
      // Bump the auto-scroll counter so the next render doesn't read the
      // prepend as "new messages appended" and scroll to bottom.
      lastScrolledCountRef.current += older.length;
      setMessages(prev => [...older.map(storedToMessage), ...prev]);
      setHasMoreOlder(has_more);
    } catch (err) {
      console.error('Failed to load older messages:', err);
      // Failed; nothing to adjust against.
      scrollAdjustRef.current = null;
    } finally {
      setLoadingOlder(false);
    }
  }

  function handleScrollContainer() {
    const el = scrollRef.current;
    if (!el) return;
    if (el.scrollTop < LAZY_LOAD_THRESHOLD_PX && hasMoreOlder && !loadingOlder) {
      void loadOlderMessages();
    }
  }

  function findPrecedingQuestion(assistantIdx: number): string | null {
    for (let i = assistantIdx - 1; i >= 0; i--) {
      if (messages[i].role === 'user') {
        return messages[i].content;
      }
    }
    return null;
  }

  function enterReplyMode(assistantIdx: number) {
    const q = findPrecedingQuestion(assistantIdx);
    if (q !== null) {
      setReplyTo({
        question: q,
        assistantMessageId: messages[assistantIdx].id ?? null
      });
      textareaRef.current?.focus();
    }
  }

  async function handleSuggestionCopy(suggestionId: number, content: string) {
    try {
      if (navigator.clipboard?.writeText) {
        await navigator.clipboard.writeText(content);
      } else {
        const ta = document.createElement('textarea');
        ta.value = content;
        ta.setAttribute('readonly', '');
        ta.style.position = 'fixed';
        ta.style.opacity = '0';
        document.body.appendChild(ta);
        ta.select();
        document.execCommand('copy');
        document.body.removeChild(ta);
      }
      setCopiedSuggestionId(suggestionId);
      if (copiedSuggestionTimerRef.current !== null) {
        window.clearTimeout(copiedSuggestionTimerRef.current);
      }
      copiedSuggestionTimerRef.current = window.setTimeout(() => {
        setCopiedSuggestionId(curr => (curr === suggestionId ? null : curr));
        copiedSuggestionTimerRef.current = null;
      }, 1500);
    } catch (err) {
      console.error('Copy failed:', err);
    }
  }

  async function handleSuggestionVote(
    assistantMessageId: number,
    suggestionId: number,
    voteType: 'up' | 'down'
  ) {
    if (!name) return;
    const list = suggestionsByMessage[assistantMessageId];
    if (!list) return;
    const row = list.find(s => s.id === suggestionId);
    if (!row) return;
    if (row.submitted_by.toLowerCase() === name.toLowerCase()) {
      // UI also hides the buttons in this case; this is a defensive guard.
      return;
    }

    const previous = row.my_vote ?? null;
    const next: 'up' | 'down' | null = previous === voteType ? null : voteType;

    // Optimistic update of the row's tallies and my_vote.
    setSuggestionsByMessage(prev => {
      const updated = (prev[assistantMessageId] ?? []).map(s => {
        if (s.id !== suggestionId) return s;
        let up = s.upvotes ?? 0;
        let down = s.downvotes ?? 0;
        // Remove the previous contribution.
        if (previous === 'up') up--;
        if (previous === 'down') down--;
        // Apply the new contribution.
        if (next === 'up') up++;
        if (next === 'down') down++;
        return { ...s, upvotes: up, downvotes: down, my_vote: next };
      });
      return { ...prev, [assistantMessageId]: updated };
    });

    try {
      await api.voteOnSuggestion(suggestionId, name, next);
    } catch (err) {
      // Revert on failure.
      setSuggestionsByMessage(prev => {
        const reverted = (prev[assistantMessageId] ?? []).map(s =>
          s.id === suggestionId ? row : s
        );
        return { ...prev, [assistantMessageId]: reverted };
      });
      console.error('Suggestion vote failed:', err);
    }
  }

  // Show the "edit will wipe votes" confirmation banner for this suggestion.
  // Editing doesn't begin until the user clicks Continue.
  function handleSuggestionEditRequest(suggestionId: number) {
    setConfirmingEditFor(prev => {
      const next = new Set(prev);
      next.add(suggestionId);
      return next;
    });
  }

  function handleSuggestionEditConfirmCancel(suggestionId: number) {
    setConfirmingEditFor(prev => {
      const next = new Set(prev);
      next.delete(suggestionId);
      return next;
    });
  }

  // Continue from the confirmation banner — drop the banner state and open
  // the textarea pre-filled with the current answer.
  function handleSuggestionEditStart(suggestion: SuggestionRow) {
    setConfirmingEditFor(prev => {
      const next = new Set(prev);
      next.delete(suggestion.id);
      return next;
    });
    setEditingSuggestion(prev => ({ ...prev, [suggestion.id]: suggestion.answer }));
  }

  function handleSuggestionEditCancel(suggestionId: number) {
    setEditingSuggestion(prev => {
      const next = { ...prev };
      delete next[suggestionId];
      return next;
    });
  }

  async function handleSuggestionEditSave(
    assistantMessageId: number,
    suggestionId: number
  ) {
    if (!name) return;
    const draft = editingSuggestion[suggestionId];
    if (draft === undefined) return;
    const trimmed = draft.trim();
    if (!trimmed) return;

    // Snapshot the previous state so we can roll back on failure.
    const previousRow = (suggestionsByMessage[assistantMessageId] ?? []).find(
      s => s.id === suggestionId
    );

    // Optimistic update: replace text AND clear vote tallies, since the
    // server wipes `suggestion_votes` for this row as part of the edit.
    setSuggestionsByMessage(prev => {
      const updated = (prev[assistantMessageId] ?? []).map(s =>
        s.id === suggestionId
          ? { ...s, answer: trimmed, upvotes: 0, downvotes: 0, my_vote: null }
          : s
      );
      return { ...prev, [assistantMessageId]: updated };
    });
    handleSuggestionEditCancel(suggestionId);

    try {
      await api.editSuggestion(suggestionId, trimmed, name);
    } catch (err) {
      console.error('Edit suggestion failed:', err);
      // Roll back to the previous text + tallies, and reopen the editor
      // with the failed draft so the user can retry.
      if (previousRow) {
        setSuggestionsByMessage(prev => {
          const reverted = (prev[assistantMessageId] ?? []).map(s =>
            s.id === suggestionId ? previousRow : s
          );
          return { ...prev, [assistantMessageId]: reverted };
        });
      }
      setEditingSuggestion(prev => ({ ...prev, [suggestionId]: trimmed }));
    }
  }

  async function toggleSuggestions(assistantIdx: number) {
    const msg = messages[assistantIdx];
    if (!msg.id) return;
    const messageId = msg.id;

    // Collapse if already open.
    if (openSuggestionsFor.has(messageId)) {
      setOpenSuggestionsFor(prev => {
        const next = new Set(prev);
        next.delete(messageId);
        return next;
      });
      return;
    }

    // Open immediately; fetch (or refetch) so the list reflects any new
    // suggestions submitted since the last expansion.
    setOpenSuggestionsFor(prev => {
      const next = new Set(prev);
      next.add(messageId);
      return next;
    });

    const question = findPrecedingQuestion(assistantIdx);
    if (!question) return;

    setLoadingSuggestionsFor(prev => {
      const next = new Set(prev);
      next.add(messageId);
      return next;
    });
    try {
      const { suggestions } = await api.getSuggestions(question, name);
      setSuggestionsByMessage(prev => ({ ...prev, [messageId]: suggestions }));
    } catch (err) {
      console.error('Failed to load suggestions:', err);
      setSuggestionsByMessage(prev => ({ ...prev, [messageId]: [] }));
    } finally {
      setLoadingSuggestionsFor(prev => {
        const next = new Set(prev);
        next.delete(messageId);
        return next;
      });
    }
  }

  // Whether the input currently looks like a slash command in progress —
  // starts with `/`, no whitespace, and we're not collecting a suggestion.
  const looksLikeCommand =
    !replyTo && input.startsWith('/') && !/[\s]/.test(input);
  const filteredCommands = looksLikeCommand
    ? SLASH_COMMANDS.filter(c => c.name.startsWith(input.toLowerCase()))
    : [];
  const showCommandPalette = looksLikeCommand && filteredCommands.length > 0;
  const safeCommandIndex =
    filteredCommands.length === 0
      ? 0
      : Math.min(commandIndex, filteredCommands.length - 1);

  function appendSystem(content: string) {
    setMessages(prev => [...prev, { role: 'system', content }]);
  }

  async function executeCommand(cmd: string) {
    if (!name) return;
    setInput('');
    setLoading(true);
    try {
      switch (cmd) {
        case '/restart': {
          if (!window.confirm('Delete every conversation under your account? This cannot be undone.')) return;
          const { deleted_messages } = await api.clearMessages(name);
          setMessages([]);
          appendSystem(`Deleted ${deleted_messages} message${deleted_messages === 1 ? '' : 's'} from your account.`);
          break;
        }
        case '/clear-votes': {
          if (!window.confirm('Clear all of your up/down votes on every message?')) return;
          const { deleted_votes } = await api.clearVotes(name);
          setMessages(prev =>
            prev.map(m => (m.role === 'assistant' ? { ...m, my_vote: null } : m))
          );
          appendSystem(`Cleared ${deleted_votes} vote${deleted_votes === 1 ? '' : 's'}.`);
          break;
        }
        case '/clean': {
          // Pure client wipe — does not touch the server.
          setMessages([]);
          break;
        }
        case '/delete-account': {
          if (!window.confirm('Permanently delete your account and all associated data?')) return;
          await api.deleteAccount(name);
          clearName(); // sends the user back to the name prompt
          break;
        }
        case '/users': {
          const { users } = await api.listUsers();
          const body =
            users.length === 0
              ? 'No users yet.'
              : `Users (${users.length}):\n${users.map(u => `- ${u}`).join('\n')}`;
          appendSystem(body);
          break;
        }
        default:
          appendSystem(`Unknown command: ${cmd}`);
      }
    } catch (err) {
      appendSystem(`Command failed: ${(err as Error).message}`);
    } finally {
      setLoading(false);
    }
  }

  async function handleCopy(messageIdx: number, content: string) {
    try {
      if (navigator.clipboard?.writeText) {
        await navigator.clipboard.writeText(content);
      } else {
        // Fallback for non-secure contexts (e.g. http://) where the Clipboard
        // API is unavailable.
        const ta = document.createElement('textarea');
        ta.value = content;
        ta.setAttribute('readonly', '');
        ta.style.position = 'fixed';
        ta.style.opacity = '0';
        document.body.appendChild(ta);
        ta.select();
        document.execCommand('copy');
        document.body.removeChild(ta);
      }
      setCopiedIdx(messageIdx);
      if (copyResetTimerRef.current !== null) {
        window.clearTimeout(copyResetTimerRef.current);
      }
      copyResetTimerRef.current = window.setTimeout(() => {
        setCopiedIdx(curr => (curr === messageIdx ? null : curr));
        copyResetTimerRef.current = null;
      }, 1500);
    } catch (err) {
      console.error('Copy failed:', err);
    }
  }

  async function handleVote(messageIdx: number, voteType: 'up' | 'down') {
    if (!name) return;
    const msg = messages[messageIdx];
    if (!msg.id) return;

    const previous = msg.my_vote ?? null;
    const next: VoteState = previous === voteType ? null : voteType;

    // Trigger the pop animation only when activating a vote (not when clearing).
    if (next !== null) {
      const key = Date.now();
      setAnimTrigger({ messageId: msg.id, voteType: next, key });
      window.setTimeout(() => {
        setAnimTrigger(curr => (curr?.key === key ? null : curr));
      }, 400);
    }

    // Optimistic update.
    setMessages(prev =>
      prev.map((m, i) => (i === messageIdx ? { ...m, my_vote: next } : m))
    );

    try {
      await api.voteOnMessage(msg.id, name, next);
    } catch (err) {
      // Revert on failure.
      setMessages(prev =>
        prev.map((m, i) => (i === messageIdx ? { ...m, my_vote: previous } : m))
      );
      console.error('Vote failed:', err);
    }
  }

  async function submit() {
    if (!input.trim() || loading || !name) return;

    // Slash command intercept: a bare command (no extra text) routes to the
    // command handler instead of the chat / suggestion flow. Anything that
    // starts with `/` but isn't a known command falls into the unknown-command
    // branch (rather than being sent to the LLM) so users don't accidentally
    // train the agent on typo'd commands.
    const trimmed = input.trim();
    if (!replyTo && trimmed.startsWith('/')) {
      const cmd = SLASH_COMMANDS.find(c => c.name === trimmed.toLowerCase());
      if (cmd) {
        await executeCommand(cmd.name);
      } else {
        setInput('');
        appendSystem(`Unknown command: ${trimmed}. Type / to see available commands.`);
      }
      return;
    }

    if (replyTo) {
      const suggested = input.trim();
      const { question, assistantMessageId } = replyTo;
      setInput('');
      setLoading(true);
      try {
        const result = await api.suggestAnswer(question, suggested, name, assistantMessageId);
        setReplyTo(null);
        // The server runs promoteWinningSuggestion after every suggestion;
        // when the result is `{ promoted: true, current_answer: suggested }`,
        // our submission is now the canonical qa_entries answer for this
        // question. We also passed `target_message_id` to the server so it
        // rewrote that specific bubble's row in `messages`. Mirror the same
        // update locally: replace ONLY the targeted bubble's content + flip
        // its Preferred flag, and bump suggestion_count on every matching
        // bubble for the question. (When the suggestion didn't win — e.g.
        // existing votes outweighed it — we just bump the count.)
        const wonPromotion = result.promoted && result.current_answer === suggested;
        setMessages(prev => {
          const next = prev.map((m, i) => {
            if (m.role !== 'assistant') return m;
            // Walk backwards to find the preceding user question for this bubble.
            let prevQ: string | null = null;
            for (let j = i - 1; j >= 0; j--) {
              if (prev[j].role === 'user') {
                prevQ = prev[j].content;
                break;
              }
            }
            if (prevQ !== question) return m;
            const isTargetedBubble =
              wonPromotion && assistantMessageId !== null && m.id === assistantMessageId;
            return {
              ...m,
              content: isTargetedBubble ? suggested : m.content,
              from_qa_entries: isTargetedBubble ? true : m.from_qa_entries,
              suggestion_count: (m.suggestion_count ?? 0) + 1
            };
          });
          return next;
        });
        // If this question already has an open suggestions panel anywhere,
        // drop its cached list so the next open re-fetches and shows the
        // submission we just made.
        setSuggestionsByMessage(prev => {
          const next: typeof prev = {};
          for (const [k, v] of Object.entries(prev)) {
            const id = Number(k);
            // Conservative: clear all caches; the panel will refetch on next open.
            // (A precise filter would require re-walking messages to map id -> question.)
            void v;
            void id;
          }
          return next;
        });
        setSuggestStatus(
          result.promoted
            ? 'Your suggestion is now the saved answer.'
            : 'Suggestion submitted. The highest-voted suggestion wins.'
        );
        setTimeout(() => setSuggestStatus(null), 4000);
      } catch (err) {
        setSuggestStatus('Error: ' + (err as Error).message);
        setTimeout(() => setSuggestStatus(null), 6000);
      } finally {
        setLoading(false);
      }
      return;
    }

    const question = input.trim();
    setInput('');
    setMessages(prev => [...prev, { role: 'user', content: question }]);
    setLoading(true);
    try {
      const res = await api.chat(question, name);
      const reply = res.answer ?? 'No response.';
      setMessages(prev => {
        // Patch the last user bubble with its id (from server) and append the assistant.
        const patched = [...prev];
        const lastUserIdx = patched.length - 1;
        if (
          lastUserIdx >= 0 &&
          patched[lastUserIdx].role === 'user' &&
          patched[lastUserIdx].id === undefined &&
          res.user_message_id !== undefined
        ) {
          patched[lastUserIdx] = { ...patched[lastUserIdx], id: res.user_message_id };
        }
        patched.push({
          id: res.assistant_message_id,
          role: 'assistant',
          content: reply,
          my_vote: null,
          suggestion_count: Number(res.suggestion_count ?? 0),
          from_qa_entries: Boolean(res.from_qa_entries)
        });
        return patched;
      });
    } catch (err) {
      setMessages(prev => [
        ...prev,
        { role: 'assistant', content: 'Error: ' + (err as Error).message }
      ]);
    } finally {
      setLoading(false);
    }
  }

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    void submit();
  }

  function handleKeyDown(e: React.KeyboardEvent<HTMLTextAreaElement>) {
    // Command-palette navigation. Arrow keys move the highlight, Tab fills the
    // textarea with the highlighted command's full name. Enter does NOT auto-
    // execute the highlighted item — execution requires the input to match a
    // command name exactly (handled by `submit()` below). This keeps the rule
    // simple: only the exact text in the box runs.
    if (showCommandPalette) {
      if (e.key === 'ArrowDown') {
        e.preventDefault();
        setCommandIndex(i => (i + 1) % filteredCommands.length);
        return;
      }
      if (e.key === 'ArrowUp') {
        e.preventDefault();
        setCommandIndex(i => (i - 1 + filteredCommands.length) % filteredCommands.length);
        return;
      }
      if (e.key === 'Tab') {
        e.preventDefault();
        setInput(filteredCommands[safeCommandIndex].name);
        return;
      }
    }
    if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing) {
      e.preventDefault();
      void submit();
    }
  }

  return (
    <div className="relative flex-1 flex flex-col min-h-0">
      {loadingOlder && (
        // Overlay-positioned so it doesn't affect the scroll container's
        // scrollHeight. Inside-the-container would shift content when the
        // indicator toggles and cause a visible jump on lazy load.
        <div className="pointer-events-none absolute top-2 left-1/2 -translate-x-1/2 z-10 text-[11px] text-chat-muted bg-chat-panel/80 backdrop-blur px-3 py-1 rounded-full border border-chat-border">
          Loading older messages...
        </div>
      )}
      <main
        ref={scrollRef}
        onScroll={handleScrollContainer}
        className="thin-scrollbar flex-1 overflow-y-auto px-4 py-6"
      >
        <div className="max-w-3xl mx-auto space-y-6">
          {messages.length === 0 && (
            <div className="text-center mt-32">
              <p className="text-2xl text-chat-text">
                {name ? `Hi ${name}, what can I help with?` : 'What can I help with?'}
              </p>
              <p className="mt-3 text-sm text-chat-muted">
                Ask a question below to start the conversation.
              </p>
            </div>
          )}
          {messages.map((msg, idx) => {
            const justCopied = copiedIdx === idx;
            if (msg.role === 'system') {
              return (
                <div key={`s-${idx}`} className="flex justify-center">
                  <div className="max-w-2xl px-3 py-2 rounded-xl bg-chat-panel/60 border border-chat-border text-xs text-chat-muted whitespace-pre-wrap text-center">
                    {msg.content}
                  </div>
                </div>
              );
            }
            if (msg.role === 'user') {
              return (
                <div key={msg.id ?? `u-${idx}`} className="flex flex-col items-end">
                  <div className="max-w-2xl px-4 py-3 rounded-2xl bg-chat-panel">
                    <p className="whitespace-pre-wrap leading-relaxed">{msg.content}</p>
                  </div>
                  <div className="mr-1 mt-1 inline-flex items-center gap-1">
                    <button
                      type="button"
                      onClick={() => void handleCopy(idx, msg.content)}
                      className={`p-1.5 rounded-md transition ${
                        justCopied
                          ? 'text-green-400 bg-chat-panel'
                          : 'text-chat-text/80 hover:text-chat-text hover:bg-chat-panel'
                      }`}
                      title={justCopied ? 'Copied' : 'Copy message'}
                      aria-label={justCopied ? 'Copied' : 'Copy message'}
                    >
                      {justCopied ? <CheckIcon className="w-4 h-4" /> : <CopyIcon className="w-4 h-4" />}
                    </button>
                  </div>
                </div>
              );
            }
            const upActive = msg.my_vote === 'up';
            const downActive = msg.my_vote === 'down';
            const canVote = msg.id !== undefined;
            const upPopKey =
              animTrigger !== null &&
              animTrigger.messageId === msg.id &&
              animTrigger.voteType === 'up'
                ? animTrigger.key
                : null;
            const downPopKey =
              animTrigger !== null &&
              animTrigger.messageId === msg.id &&
              animTrigger.voteType === 'down'
                ? animTrigger.key
                : null;
            const suggestionsOpen = msg.id !== undefined && openSuggestionsFor.has(msg.id);
            const suggestionsLoading = msg.id !== undefined && loadingSuggestionsFor.has(msg.id);
            const suggestionRows = msg.id !== undefined ? suggestionsByMessage[msg.id] : undefined;
            return (
              <div key={msg.id ?? `a-${idx}`} className="flex flex-col items-start">
                {msg.from_qa_entries && <PreferredBadge />}
                <div className="max-w-2xl px-4 pt-2 pb-1">
                  <p className="whitespace-pre-wrap leading-relaxed">{msg.content}</p>
                </div>
                <div className="ml-4 inline-flex items-center gap-1 flex-wrap">
                  <button
                    type="button"
                    onClick={() => void handleCopy(idx, msg.content)}
                    className={`p-1.5 rounded-md transition ${
                      justCopied
                        ? 'text-green-400 bg-chat-panel'
                        : 'text-chat-text/80 hover:text-chat-text hover:bg-chat-panel'
                    }`}
                    title={justCopied ? 'Copied' : 'Copy message'}
                    aria-label={justCopied ? 'Copied' : 'Copy message'}
                  >
                    {justCopied ? <CheckIcon className="w-4 h-4" /> : <CopyIcon className="w-4 h-4" />}
                  </button>
                  <button
                    type="button"
                    onClick={() => canVote && handleVote(idx, 'up')}
                    disabled={!canVote}
                    className={`p-1.5 rounded-md transition disabled:opacity-30 ${
                      upActive
                        ? 'text-green-400 bg-chat-panel'
                        : 'text-chat-text/80 hover:text-chat-text hover:bg-chat-panel'
                    }`}
                    title="Upvote"
                    aria-label="Upvote"
                    aria-pressed={upActive}
                  >
                    <ThumbUpIcon
                      key={upPopKey !== null ? `up-${msg.id}-${upPopKey}` : `up-${msg.id}-still`}
                      className={`w-4 h-4 ${upPopKey !== null ? 'animate-vote-pop' : ''}`}
                      filled={upActive}
                    />
                  </button>
                  <button
                    type="button"
                    onClick={() => canVote && handleVote(idx, 'down')}
                    disabled={!canVote}
                    className={`p-1.5 rounded-md transition disabled:opacity-30 ${
                      downActive
                        ? 'text-red-400 bg-chat-panel'
                        : 'text-chat-text/80 hover:text-chat-text hover:bg-chat-panel'
                    }`}
                    title="Downvote"
                    aria-label="Downvote"
                    aria-pressed={downActive}
                  >
                    <ThumbDownIcon
                      key={downPopKey !== null ? `down-${msg.id}-${downPopKey}` : `down-${msg.id}-still`}
                      className={`w-4 h-4 ${downPopKey !== null ? 'animate-vote-pop' : ''}`}
                      filled={downActive}
                    />
                  </button>
                  <button
                    type="button"
                    onClick={() => enterReplyMode(idx)}
                    className="ml-1 inline-flex items-center gap-1 px-1.5 py-0.5 rounded-md text-[11px] text-chat-muted hover:text-chat-text hover:bg-chat-panel transition"
                    title="Suggest a better answer"
                    aria-label="Suggest a better answer"
                  >
                    <BulbIcon className="w-3 h-3" />
                    <span>Suggest</span>
                  </button>
                  {(msg.suggestion_count ?? 0) > 1 && (
                    <button
                      type="button"
                      onClick={() => canVote && void toggleSuggestions(idx)}
                      disabled={!canVote}
                      className={`inline-flex items-center gap-1 px-1.5 py-0.5 rounded-md text-[11px] transition disabled:opacity-30 ${
                        suggestionsOpen
                          ? 'text-chat-text bg-chat-panel'
                          : 'text-chat-muted hover:text-chat-text hover:bg-chat-panel'
                      }`}
                      title="See other suggestions"
                      aria-label="See other suggestions"
                      aria-expanded={suggestionsOpen}
                    >
                      <MessageIcon className="w-3 h-3" />
                      <span>See other suggestions</span>
                    </button>
                  )}
                </div>
                {suggestionsOpen && (
                  <div className="ml-4 mt-2 max-w-2xl w-full pl-4 border-l-2 border-chat-border">
                    {suggestionsLoading && suggestionRows === undefined ? (
                      <div className="py-2 text-xs text-chat-muted">Loading suggestions...</div>
                    ) : suggestionRows === undefined || suggestionRows.length === 0 ? (
                      <div className="py-2 text-xs text-chat-muted">
                        No suggestions yet.
                      </div>
                    ) : (
                      <ul className="space-y-3 py-1">
                        {suggestionRows.map(s => {
                          const isOwner =
                            !!name && name.toLowerCase() === s.submitted_by.toLowerCase();
                          const isEditing = Object.prototype.hasOwnProperty.call(
                            editingSuggestion,
                            s.id
                          );
                          const isConfirmingEdit = confirmingEditFor.has(s.id);
                          const sUp = s.upvotes ?? 0;
                          const sDown = s.downvotes ?? 0;
                          const net = sUp - sDown;
                          const sUpActive = s.my_vote === 'up';
                          const sDownActive = s.my_vote === 'down';
                          const sJustCopied = copiedSuggestionId === s.id;
                          const assistantId = msg.id;

                          return (
                            <li key={s.id} className="space-y-1">
                              {isEditing ? (
                                <div className="space-y-2">
                                  <textarea
                                    value={editingSuggestion[s.id]}
                                    onChange={e =>
                                      setEditingSuggestion(prev => ({
                                        ...prev,
                                        [s.id]: e.target.value
                                      }))
                                    }
                                    rows={3}
                                    className="thin-scrollbar w-full bg-chat-input border border-chat-border rounded-lg px-3 py-2 text-xs text-chat-text focus:outline-none focus:ring-0 resize-none"
                                  />
                                  <div className="flex gap-2">
                                    <button
                                      type="button"
                                      onClick={() =>
                                        assistantId !== undefined &&
                                        void handleSuggestionEditSave(assistantId, s.id)
                                      }
                                      disabled={!(editingSuggestion[s.id] ?? '').trim()}
                                      className="px-2 py-1 rounded bg-white text-black text-[11px] font-medium disabled:opacity-40"
                                    >
                                      Save
                                    </button>
                                    <button
                                      type="button"
                                      onClick={() => handleSuggestionEditCancel(s.id)}
                                      className="px-2 py-1 rounded bg-chat-panel border border-chat-border text-[11px] text-chat-text"
                                    >
                                      Cancel
                                    </button>
                                  </div>
                                </div>
                              ) : (
                                <p className="whitespace-pre-wrap leading-relaxed text-xs text-chat-text/90">
                                  {s.answer}
                                </p>
                              )}
                              <div className="flex items-center gap-2 text-[10px] text-chat-muted">
                                <span>
                                  by {s.submitted_by}
                                  {isOwner ? ' (you)' : ''}
                                </span>
                                <span aria-hidden="true">·</span>
                                <span>{new Date(s.created_at).toLocaleString()}</span>
                              </div>
                              {!isEditing && isConfirmingEdit && (
                                <div className="mt-1 rounded-lg border border-yellow-400/40 bg-yellow-400/10 px-3 py-2 space-y-2">
                                  <p className="text-[11px] text-yellow-200">
                                    Editing your suggestion will remove all the current votes.
                                  </p>
                                  <div className="flex gap-2">
                                    <button
                                      type="button"
                                      onClick={() => handleSuggestionEditStart(s)}
                                      className="px-2 py-1 rounded bg-white text-black text-[11px] font-medium"
                                    >
                                      Continue
                                    </button>
                                    <button
                                      type="button"
                                      onClick={() => handleSuggestionEditConfirmCancel(s.id)}
                                      className="px-2 py-1 rounded bg-chat-panel border border-chat-border text-[11px] text-chat-text"
                                    >
                                      Cancel
                                    </button>
                                  </div>
                                </div>
                              )}
                              {!isEditing && !isConfirmingEdit && (
                                <div className="inline-flex items-center gap-1">
                                  <button
                                    type="button"
                                    onClick={() => void handleSuggestionCopy(s.id, s.answer)}
                                    className={`p-1.5 rounded-md transition ${
                                      sJustCopied
                                        ? 'text-green-400 bg-chat-panel'
                                        : 'text-chat-text/70 hover:text-chat-text hover:bg-chat-panel'
                                    }`}
                                    title={sJustCopied ? 'Copied' : 'Copy suggestion'}
                                    aria-label={sJustCopied ? 'Copied' : 'Copy suggestion'}
                                  >
                                    {sJustCopied ? (
                                      <CheckIcon className="w-4 h-4" />
                                    ) : (
                                      <CopyIcon className="w-4 h-4" />
                                    )}
                                  </button>
                                  {/*
                                    Up/down only render for non-owners. The
                                    submitter already contributes an implicit
                                    +1 to the promotion score (computed in
                                    `promote.ts` via COUNT(DISTINCT submitted_by))
                                    and the server rejects self-votes — so
                                    putting the buttons on the owner's own
                                    row would just be inert decoration.
                                  */}
                                  {!isOwner && (
                                    <>
                                      <button
                                        type="button"
                                        onClick={() =>
                                          assistantId !== undefined &&
                                          void handleSuggestionVote(assistantId, s.id, 'up')
                                        }
                                        className={`p-1.5 rounded-md transition ${
                                          sUpActive
                                            ? 'text-green-400 bg-chat-panel'
                                            : 'text-chat-text/70 hover:text-chat-text hover:bg-chat-panel'
                                        }`}
                                        title="Upvote suggestion"
                                        aria-label="Upvote suggestion"
                                        aria-pressed={sUpActive}
                                      >
                                        <ThumbUpIcon className="w-4 h-4" filled={sUpActive} />
                                      </button>
                                      <button
                                        type="button"
                                        onClick={() =>
                                          assistantId !== undefined &&
                                          void handleSuggestionVote(assistantId, s.id, 'down')
                                        }
                                        className={`p-1.5 rounded-md transition ${
                                          sDownActive
                                            ? 'text-red-400 bg-chat-panel'
                                            : 'text-chat-text/70 hover:text-chat-text hover:bg-chat-panel'
                                        }`}
                                        title="Downvote suggestion"
                                        aria-label="Downvote suggestion"
                                        aria-pressed={sDownActive}
                                      >
                                        <ThumbDownIcon className="w-4 h-4" filled={sDownActive} />
                                      </button>
                                    </>
                                  )}
                                  {isOwner && (
                                    <button
                                      type="button"
                                      onClick={() => handleSuggestionEditRequest(s.id)}
                                      className="p-1.5 rounded-md text-chat-text/70 hover:text-chat-text hover:bg-chat-panel transition"
                                      title="Edit your suggestion"
                                      aria-label="Edit your suggestion"
                                    >
                                      <EditIcon className="w-4 h-4" />
                                    </button>
                                  )}
                                  {(sUp > 0 || sDown > 0) && (
                                    <span className="ml-1 text-[10px] text-chat-muted">
                                      {net > 0 ? `+${net}` : net}
                                    </span>
                                  )}
                                </div>
                              )}
                            </li>
                          );
                        })}
                      </ul>
                    )}
                  </div>
                )}
              </div>
            );
          })}
          {loading && (
            <div className="flex justify-start">
              <div className="px-4 py-3 text-chat-muted">Thinking...</div>
            </div>
          )}
        </div>
      </main>
      <footer className="px-4 py-4">
        {suggestStatus && (
          <div className="max-w-[768px] mx-auto mb-2 px-4 py-2 rounded-2xl bg-chat-panel border border-chat-border text-xs text-chat-text text-center">
            {suggestStatus}
          </div>
        )}
        {replyTo && (
          <div className="max-w-[768px] mx-auto mb-2 flex items-center gap-2 px-4 py-2 rounded-2xl bg-chat-panel border border-chat-border text-xs">
            <BulbIcon className="w-3.5 h-3.5 text-chat-muted shrink-0" />
            <span className="flex-1 truncate text-chat-muted">
              Suggesting answer for:{' '}
              <span className="text-chat-text">{replyTo.question}</span>
            </span>
            <button
              type="button"
              onClick={() => setReplyTo(null)}
              className="text-chat-muted hover:text-chat-text shrink-0 px-1"
              aria-label="Cancel suggestion"
            >
              ×
            </button>
          </div>
        )}
        <form onSubmit={handleSubmit} className="relative max-w-[768px] mx-auto">
          {showCommandPalette && (
            <div className="absolute bottom-full left-0 right-0 mb-2 rounded-2xl bg-chat-panel border border-chat-border shadow-lg overflow-hidden z-10">
              <div className="px-3 py-2 text-[10px] uppercase tracking-wide text-chat-muted border-b border-chat-border">
                Command helpers
              </div>
              <ul className="max-h-64 overflow-y-auto thin-scrollbar">
                {filteredCommands.map((c, i) => (
                  <li key={c.name}>
                    <button
                      type="button"
                      onClick={() => {
                        // Click autocompletes the input. Execution still
                        // requires the user to press Enter or hit Submit,
                        // matching the "exact text in the box" rule.
                        setInput(c.name);
                        textareaRef.current?.focus();
                      }}
                      onMouseEnter={() => setCommandIndex(i)}
                      className={`w-full text-left px-3 py-2 flex flex-col gap-0.5 transition ${
                        i === safeCommandIndex ? 'bg-chat-input' : 'hover:bg-chat-input/60'
                      }`}
                    >
                      <span className="font-mono text-sm text-chat-text">{c.name}</span>
                      <span className="text-xs text-chat-muted">{c.description}</span>
                    </button>
                  </li>
                ))}
              </ul>
            </div>
          )}
          <div
            className={
              isMultiLine
                ? 'rounded-3xl bg-chat-input border border-chat-border p-2'
                : 'rounded-3xl bg-chat-input border border-chat-border flex items-end gap-2 p-2 pl-5'
            }
          >
            <textarea
              ref={textareaRef}
              value={input}
              onChange={e => setInput(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder={replyTo ? 'Type your suggested answer...' : 'Ask anything'}
              rows={1}
              className={`thin-scrollbar bg-transparent border-0 resize-none py-1.5 text-chat-text placeholder-chat-muted focus:outline-none focus:ring-0 overflow-y-hidden leading-6 block ${
                isMultiLine ? 'w-full px-3' : 'flex-1'
              }`}
              style={{ maxHeight: TEXTAREA_MAX_HEIGHT }}
            />
            <div className={isMultiLine ? 'flex justify-end' : 'shrink-0'}>
              <button
                type="submit"
                disabled={loading || !input.trim()}
                className="w-9 h-9 rounded-full bg-white text-black flex items-center justify-center disabled:opacity-30"
                aria-label={replyTo ? 'Submit suggestion' : 'Send'}
              >
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className="w-4 h-4" aria-hidden="true">
                  <path fillRule="evenodd" d="M10 17a.75.75 0 01-.75-.75V5.612L5.29 9.77a.75.75 0 01-1.08-1.04l5.25-5.5a.75.75 0 011.08 0l5.25 5.5a.75.75 0 11-1.08 1.04l-3.96-4.158V16.25A.75.75 0 0110 17z" clipRule="evenodd" />
                </svg>
              </button>
            </div>
          </div>
          <p className="text-xs text-chat-muted text-center mt-3">
            Your inquiries and answers train the agent.
          </p>
        </form>
      </footer>
    </div>
  );
}
